// Every scheduled job, in one list.
//
// Before Phase 2c the same fact lived in three places that nothing kept in
// step: vercel.json's "crons", the /internal mounts in app.ts, and the route
// docs. A job added to one and forgotten in another either never ran or ran
// with no route behind it. This list is the one place; the others are derived
// from it or checked against it:
//
//   - the /internal/*/run routes are mounted from it (src/routes/jobRoutes.ts);
//   - vercel.json's "crons" must equal vercelCrons() (tests/unit/jobRegistry
//     .test.ts fails on any difference; `npm run jobs:crontab -- --vercel`
//     prints the section to paste);
//   - `npm run jobs:crontab` prints a crontab for a deployment that is not on
//     Vercel, so a self-hosted hub schedules exactly the same jobs.
//
// Pure data by construction — no imports from the app — so the crontab script
// and the test can read it without booting anything. What each job DOES is in
// src/jobs/runners.ts, keyed on the same ids.
//
// Every schedule is UTC (Vercel Cron's only time zone, and cron's default).
// A job that must honour a hub's local time runs more often and decides per
// hub whether it is due: the resident digest runs hourly and sends to a hub
// only in the hour that hub chose, in the hub's own time zone.

import type { PluginId } from "../models/hubSettings.js";

export interface JobSpec {
  /** Stable id, also the key into the runner table. */
  readonly id: string;
  /** The plugin this job belongs to. `plugin.<id>.enabled` off skips it per hub. */
  readonly plugin: PluginId;
  /** Path under /internal. Vercel calls it with a GET and the CRON_SECRET bearer. */
  readonly path: string;
  /** Five-field cron expression, UTC. */
  readonly schedule: string;
  /** One line for the route docs and the crontab comment. */
  readonly description: string;
  /**
   * Older paths still mounted to the same job but never scheduled. Each one
   * is on its way out and says why beside it.
   */
  readonly deprecatedPaths?: readonly string[];
}

/** Where the job routes are mounted in the Express app. */
export const JOBS_MOUNT = "/internal";

/**
 * What Vercel puts in front of every Express path: `/api/:path*` is rewritten
 * to the one function, and the prefix is stripped before Express sees it.
 */
export const VERCEL_API_PREFIX = "/api";

export const JOBS: readonly JobSpec[] = [
  {
    id: "meeting_summary",
    plugin: "meeting_summary",
    path: "/meeting-summary/run",
    schedule: "30 11 * * *",
    description: "Meeting discovery and summarization, per hub that configured a source",
  },
  {
    id: "news_sync",
    plugin: "news_sync",
    path: "/news-sync/run",
    schedule: "0 12 * * *",
    description: "News feed to announcements, per hub that configured a feed",
    // Production's vercel.json on `main` schedules the old name until the
    // multi-tenant cutover deploys this list; removed then, together with its
    // entry in scripts/place-name-allowlist.txt.
    deprecatedPaths: ["/floyd-news-sync/run"],
  },
  {
    id: "digest",
    plugin: "digest",
    path: "/digest/run",
    // Hourly: each hub is mailed in its own plugin.digest.send_hour, read in
    // its identity.timezone. See runDigestForHub.
    schedule: "0 * * * *",
    description: "Resident email digest, per hub in its own send hour",
  },
  {
    id: "admin_digest",
    plugin: "admin_digest",
    path: "/admin-digest/run",
    schedule: "30 13 * * *",
    description: "Admin review-queue digest, per hub",
  },
];

export function jobById(id: string): JobSpec | undefined {
  return JOBS.find((j) => j.id === id);
}

/** The full Express path of a job route, e.g. `/internal/digest/run`. */
export function internalPath(job: JobSpec, path: string = job.path): string {
  return `${JOBS_MOUNT}${path}`;
}

/** vercel.json's "crons" section, in registry order. */
export function vercelCrons(): Array<{ path: string; schedule: string }> {
  return JOBS.map((job) => ({
    path: `${VERCEL_API_PREFIX}${internalPath(job)}`,
    schedule: job.schedule,
  }));
}

/**
 * A crontab for a deployment that is not on Vercel. Each line GETs the job's
 * route with the CRON_SECRET bearer, exactly as Vercel Cron does. `baseUrl`
 * and the secret are left as shell variables unless given, so the output can
 * be installed as-is on a host that exports them.
 */
export function crontab(
  opts: { baseUrl?: string; prefix?: string } = {},
): string {
  const base = opts.baseUrl ?? "${CIVIC_CRON_BASE_URL}";
  const prefix = opts.prefix ?? VERCEL_API_PREFIX;
  const lines = [
    "# civic-hub scheduled jobs — generated by `npm run jobs:crontab` from src/jobs/registry.ts.",
    "# Times are UTC. Each run covers every active hub; a hub with the plugin off is skipped.",
    "CRON_TZ=UTC",
  ];
  for (const job of JOBS) {
    lines.push(`# ${job.id}: ${job.description}`);
    lines.push(
      `${job.schedule} curl -fsS -H "Authorization: Bearer $CRON_SECRET" "${base}${prefix}${internalPath(job)}"`,
    );
  }
  return `${lines.join("\n")}\n`;
}
